### ISSUE TITLE
clean up and finish content cards

### ISSUE THREAD

**Issue by timothyfcook** [saxifrage/caac-map#22]
- [x] Pick a good char-limit and truncate text (use "...", later maybe I can go in and clean up data so all descriptions are within our chart-limit)
- [x] Make boxes a bit wider (so they can be shorter)
- [ ] Set rules so that entire box appears on screen (in some cases, clicking on box made it appear 80% off screen forcing a scroll down ) --- this might be tricky.
- [ ] implement design detail for difficulty: @chelseaerdner and I talked about highlighting the appropriate difficulty panel with green/yellow/red and making any panels above it greyed-out/opaque. For hard difficulty it would show all three: green, yellow, red.
- [x] Make the background images at tops of cards a little less dark.
- [x] Card title-hyperlinks should change color w hover
- [ ] remove word "Activity" before local/digital type
- [ ] if age range reads e.g. "9 - 90", change it to show just "9+"

**Comment by timothyfcook** [comment]
Make the background images at tops of cards a little less dark.

**Comment by timothyfcook** [comment]
- Card title-hyperlinks should change color w hover

**Comment by cameronscott137** [comment]
**Completed:**
- Resource descriptions have been truncated to 300 chars, and Org descriptions have been truncated to 150.
- Popover widened to 300px
- Popover overlay opacity lightened
- Adds hover state to popover title link
- Removes word "activity" before local/digital type
- 9–90 age range now reads "9+."

**To-Do**
- Set rules so that entire popover appears on screen. You're right @timothyfcook, this is gonna be a bit tougher. Splitting this out to a separate issue.
- Implement design detail for difficulty. This isn't big, but since it'll require @chelseaerdner's input, too, going to split it out to separate issue.

**Comment by timothyfcook** [comment]
I'm still seeing:
- [x] remove word "Activity" before local/digital type
- [x] if age range reads e.g. "9 - 90", change it to show just "9+"

**Comment by cameronscott137** [comment]
Both updated. Just needed to commit the view.

Keep in mind, only resources labeled 9–90 will show up as 9+. There are resources in the mix that are 10–90 and 11–90, as well. When we begin to utilize user data, will want to provide a dropdown or some similar way to enforce consistency, but in the interim, I can account for those cases, as well?

**Comment by timothyfcook** [comment]
Ah, yeah. Can we do it so that any age range that has a " - 90" in it is replaced with "+" ?
